### ISSUE TITLE
Handling categorical columns

### ISSUE THREAD

**Issue by tkharrat** [tcapelle/TimeSeries_fastai#12]
As suggested in the fastai forum, it would be interesting to handle categorical features in a similar way to what is done in fastai2 using embedding layers. This is rather a feature request not a bug so feel free to close tnis issue if it is not the right place to report it

**Comment by rsayn** [comment]
Hello, I'm also interested in this feature.
I recently developed a Fastai wrapper of the [category-encoders](https://pypi.org/project/category-encoders/) library; I also extended it with a couple more "experimental" category encoders based on stuff like FastText embeddings.

I'll leave the link here, I hope it helps:
[https://github.com/kireygroup/fastai-category-encoders](https://github.com/kireygroup/fastai-category-encoders)

**Comment by tcapelle** [comment]
We should probably move to `tsai` to implement these features and unify our efforts.
