### ISSUE TITLE
[Documentation] Github Pages returning 404 on (most) documentation sections

### ISSUE THREAD

**Issue by rsayn** [tcapelle/TimeSeries_fastai#13]
Hi, I'm trying out the library but I'm having troubles with the documentation website. As mentioned, most of the pages there return a 404 error.

An example: [https://tcapelle.github.io/timeseries_fastai/models.html](https://tcapelle.github.io/timeseries_fastai/models.html)

**Comment by tcapelle** [comment]
Thanks to let me know, I think is a problem of nbdev.
I will put the sidebar on custom to solve this issue.

**Comment by tcapelle** [comment]
shuold be good now.
Anyway, I will suggest to read the jupyter notebooks directly instead of the doc, so you can play with the code.
