### ISSUE TITLE
Error using timeseries with >1 channels with inception and xresnet

### ISSUE THREAD

**Issue by maxmatical** [tcapelle/TimeSeries_fastai#4]
For example, given ni > 1, when I try to create a model using inception or xresnet, I get the following error

`RuntimeError: Given groups=1, weight of size 32 1 39, expected input[128, 2, 1024] to have 1 channels, but got 2 channels instead`

**Comment by maxmatical** [comment]
I believe the error in inception.py is this line of code

`        im = SequentialEx(InceptionModule(1 if d==0 else n_ks*nb_filters, kss=kss, bottleneck_size=bottleneck_size))`

and for xresnet:

`        stem.append(conv_layer(1, 64, ks=9, stride=1))`

**Comment by tcapelle** [comment]
Just made a push with the changes, check if it works now.
