### ISSUE TITLE
Update to Fastai v2.0.x

### ISSUE THREAD

**Issue by rsayn** [tcapelle/TimeSeries_fastai#9]
Hello, I see this package is using the old Fastai V2 library (`fastai2`).
I was wondering if you had any plans to update to version 2.0.x of the `fastai` package: https://pypi.org/project/fastai/
Thanks in advance

**Comment by williamsdoug** [comment]
Tested installing directly from GitHub.  Notebooks in top-level and nbs/04_testing.ipynb all work.  Have created a pull request with  some cosmetic changes, including output for 03_benchmark.ipynb without CUDA out of memory error..

Thanks!

**Comment by tcapelle** [comment]
it is done, i will test more tomorrow.
